Updated to Gradle 7.0.

diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,19 +1,6 @@
 #!/bin/sh
-#
-# Copyright 2020 Luis Mejia
-#
-# Licensed under the Apache License, Version 2.0 (the "License");
-# you may not use this file except in compliance with the License.
-# You may obtain a copy of the License at
-#
-#     http://www.apache.org/licenses/LICENSE-2.0
-#
-# Unless required by applicable law or agreed to in writing, software
-# distributed under the License is distributed on an "AS IS" BASIS,
-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-# See the License for the specific language governing permissions and
-# limitations under the License.
-#
+# Copyright 2020-2021 GlitchyByte
+# SPDX-License-Identifier: Apache-2.0
 
 # Run app!
 
@@ -32,12 +19,20 @@ fi
 # We did this already for speed. Read above.
 #gradleProperties=$(./gradlew properties)
 
+# Get build directory.
+buildDir=$(echo "$gradleProperties" | sed -n 's/^buildDir: \(.*\)/\1/p')
+if test -z buildDir; then
+  echo "Build directory not found!"
+  exit 2
+fi
+
 # Get distribution directory.
-distDir=$(echo "$gradleProperties" | sed -n 's/^distsDir: \(.*\)/\1/p')
-if test -z distDir; then
+distsDirName=$(echo "$gradleProperties" | sed -n 's/^distsDirName: \(.*\)/\1/p')
+if test -z distsDirName; then
   echo "Distribution directory not found!"
   exit 2
 fi
+distDir="$buildDir/$distsDirName"
 
 # Get application name.
 appName=$(echo "$gradleProperties" | sed -n 's/^applicationName: \(.*\)/\1/p')
@@ -46,18 +41,15 @@ if test -z appName; then
   exit 2
 fi
 
+# Get version.
+version=$(echo "$gradleProperties" | sed -n 's/^version: \(.*\)/\1/p')
+if test -z version; then
+  echo "Version not found!"
+  exit 2
+fi
+
 # Get tar path.
-tarPath=""
-for filename in "$distDir"/*.tar; do
-  if test ! -f "$filename"; then
-    continue
-  fi
-  if test ! -z "$tarPath"; then
-    echo "More than one distribution found!"
-    exit 2
-  fi
-  tarPath="$filename"
-done
+tarPath="$distDir/$appName-$version.tar"
 if test -z "$tarPath"; then
   echo "No distribution found!"
   exit 2
